"""add column created_by

Revision ID: eb3b88c5fb7e
Revises: f1d72d9af026
Create Date: 2022-06-22 23:21:18.890671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3b88c5fb7e'
down_revision = 'f1d72d9af026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'updated_by')
    # ### end Alembic commands ###
