"""add column created_by

Revision ID: f1d72d9af026
Revises: 9720b4684ced
Create Date: 2022-06-22 23:13:03.176386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d72d9af026'
down_revision = '9720b4684ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created_by')
    # ### end Alembic commands ###
